[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.119.0"
uvicorn = {extras = ["standart"], version = "^0.37.0"}
pydantic = {extras = ["email"], version = "^2.12.0"}
pydantic-settings = "^2.11.0"
